"""
Notification dispatch + privacy audit report.

  send_webhook(url, payload)
      POST a JSON body to the user's webhook URL when a job finishes.

  send_email(...)
      SMTP delivery via Python stdlib (no extra deps). User configures
      via environment variables:
          ARCLAP_SMTP_HOST, ARCLAP_SMTP_PORT (default 587),
          ARCLAP_SMTP_USER, ARCLAP_SMTP_PASS,
          ARCLAP_SMTP_FROM (default = SMTP_USER)

  build_audit_report(job_dict) -> str
      Builds an HTML compliance report. Saved alongside the output as
      <output>.audit.html so the user can open or print to PDF.
"""

from __future__ import annotations

import json
import os
import smtplib
import ssl
import time
import urllib.error
import urllib.request
from datetime import datetime
from email.message import EmailMessage
from pathlib import Path
from typing import Any


def send_webhook(url: str, payload: dict) -> tuple[bool, str]:
    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as r:
            return True, f"HTTP {r.status}"
    except urllib.error.URLError as e:
        return False, f"URLError: {e}"
    except Exception as e:
        return False, f"{type(e).__name__}: {e}"


def send_email(*, to: str, subject: str, body: str,
               attachments: list[Path] | None = None) -> tuple[bool, str]:
    host = os.environ.get("ARCLAP_SMTP_HOST")
    if not host:
        return False, "ARCLAP_SMTP_HOST not set; skipping email"
    port = int(os.environ.get("ARCLAP_SMTP_PORT", "587"))
    user = os.environ.get("ARCLAP_SMTP_USER", "")
    pwd = os.environ.get("ARCLAP_SMTP_PASS", "")
    sender = os.environ.get("ARCLAP_SMTP_FROM", user)

    msg = EmailMessage()
    msg["From"] = sender
    msg["To"] = to
    msg["Subject"] = subject
    msg.set_content(body)
    for att in (attachments or []):
        if att.exists():
            with open(att, "rb") as f:
                msg.add_attachment(
                    f.read(), maintype="application", subtype="octet-stream",
                    filename=att.name,
                )

    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP(host, port, timeout=20) as s:
            s.starttls(context=ctx)
            if user:
                s.login(user, pwd)
            s.send_message(msg)
        return True, "sent"
    except Exception as e:
        return False, f"{type(e).__name__}: {e}"


def build_audit_report(job: dict, output_path: str | Path) -> Path:
    """Render an HTML privacy/compliance audit report next to the output."""
    out = Path(output_path)
    report = out.with_suffix(out.suffix + ".audit.html")

    settings = job.get("settings", {}) or {}
    started = datetime.fromtimestamp(job.get("started_at") or time.time())
    finished = datetime.fromtimestamp(job.get("finished_at") or time.time())
    dur_s = max(0, (job.get("finished_at") or 0) - (job.get("started_at") or 0))

    rows = []
    for k, v in settings.items():
        rows.append(
            f"<tr><td>{escape(str(k))}</td><td><code>{escape(json.dumps(v))}</code></td></tr>"
        )
    settings_html = "\n".join(rows) or "<tr><td colspan='2'><em>(default settings)</em></td></tr>"

    html = f"""<!DOCTYPE html>
<html><head>
<meta charset='UTF-8'>
<title>Arclap Privacy Audit — {escape(job.get('id', ''))}</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 760px;
         margin: 40px auto; padding: 0 24px; color: #1f2d3d; }}
  h1 {{ margin-bottom: 4px; }}
  .sub {{ color: #718096; margin-bottom: 28px; }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 14px 24px;
          background: #f7f8fb; padding: 18px 22px; border-radius: 10px;
          border: 1px solid #e1e5ed; margin-bottom: 22px; }}
  .grid dt {{ color: #4a5568; font-size: 0.9em; }}
  .grid dd {{ margin: 0; font-weight: 600; font-family: monospace; font-size: 0.95em; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th, td {{ padding: 8px 10px; text-align: left; border-bottom: 1px solid #e1e5ed;
            font-size: 0.92em; }}
  th {{ background: #f1f3f7; font-weight: 600; }}
  code {{ background: #f1f3f7; padding: 1px 6px; border-radius: 3px; }}
  .stamp {{ margin-top: 32px; padding: 16px; background: #f7f8fb;
            border-left: 3px solid #6366f1; border-radius: 4px; font-size: 0.9em; }}
</style></head>
<body>
  <h1>Privacy &amp; Processing Audit</h1>
  <p class='sub'>Generated by Arclap Timelapse Cleaner · job <code>{escape(job.get('id', ''))}</code></p>

  <h2>Job summary</h2>
  <dl class='grid'>
    <dt>Job ID</dt>            <dd>{escape(job.get('id', ''))}</dd>
    <dt>Mode</dt>              <dd>{escape(job.get('mode', ''))}</dd>
    <dt>Input kind</dt>        <dd>{escape(job.get('kind', ''))}</dd>
    <dt>Input reference</dt>   <dd style='word-break:break-all'>{escape(job.get('input_ref', ''))}</dd>
    <dt>Output</dt>            <dd style='word-break:break-all'>{escape(str(out))}</dd>
    <dt>Status</dt>            <dd>{escape(job.get('status', ''))}</dd>
    <dt>Started at</dt>        <dd>{started.isoformat(timespec='seconds')}</dd>
    <dt>Finished at</dt>       <dd>{finished.isoformat(timespec='seconds')}</dd>
    <dt>Duration</dt>          <dd>{int(dur_s)} s</dd>
    <dt>Project</dt>           <dd>{escape(str(job.get('project_id') or '—'))}</dd>
  </dl>

  <h2>Settings applied</h2>
  <table>
    <thead><tr><th>Parameter</th><th>Value</th></tr></thead>
    <tbody>{settings_html}</tbody>
  </table>

  <div class='stamp'>
    <strong>Privacy attestation.</strong>
    All processing occurred locally on the operator's machine. No frames
    or detections were transmitted to third parties. The settings above
    govern what was redacted (faces, vehicles, etc.). Open this file in
    a browser and use Print → Save as PDF to archive a signed copy.
  </div>
</body></html>"""

    report.write_text(html, encoding="utf-8")
    return report


def escape(s: str) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;").replace("'", "&#39;"))
