"""Render a confusion matrix from eval_csi.py output.

Reads the JSON written by scripts/eval_csi.py, builds a class-vs-class
confusion matrix from the per-class TP/FP/FN, and emits an interactive
HTML heatmap (no JS dependencies — pure inline SVG/CSS).

Usage
-----
    python scripts/confusion_matrix_view.py _outputs/eval_2026-05-01.json _outputs/eval_2026-05-01_confusion.html

Open the generated .html in a browser; hover cells for exact counts.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def render_html(eval_report: dict) -> str:
    pr = eval_report.get("per_class_pr", {})
    if not pr:
        return "<p>No per_class_pr in eval report.</p>"

    classes = sorted(int(c) for c in pr.keys())
    n = len(classes)
    title = f"CSI confusion — {eval_report.get('model', '')}"

    # Build a "diagonal-only" matrix from TP/FP/FN. Without raw match logs
    # we can't tell WHICH class each FP was confused with, so off-diagonal
    # is collapsed into a single "FP" column for visualisation.
    cells: list[list[int]] = [[0] * (n + 1) for _ in range(n)]
    for r, cid in enumerate(classes):
        m = pr[str(cid)]
        cells[r][r] = m["tp"]
        cells[r][n] = m["fp"]   # off-diagonal lump

    max_val = max((max(row) for row in cells), default=1)

    def color(v: int) -> str:
        if v == 0:
            return "#fff"
        # log scale into a single-hue ramp
        import math
        t = math.log1p(v) / math.log1p(max_val) if max_val > 0 else 0
        # red for off-diagonal-ish, blue-green for TP — simpler: warmth ramp
        return f"hsl(210, 70%, {100 - int(t * 50)}%)"

    rows_html = []
    for r, cid in enumerate(classes):
        cells_html = []
        for c in range(n + 1):
            v = cells[r][c]
            label = ("FP" if c == n else f"class {classes[c]}")
            tip = f"truth={cid}, pred={label}, n={v}"
            cells_html.append(
                f'<td style="background:{color(v)}" title="{tip}">{v}</td>'
            )
        rows_html.append(f"<tr><th>{cid}</th>{''.join(cells_html)}</tr>")

    head = "<th></th>" + "".join(f"<th>{c}</th>" for c in classes) + "<th>FP</th>"

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>
  body {{ font: 14px system-ui; padding: 24px; background: #fafafa; }}
  table {{ border-collapse: collapse; }}
  th, td {{ padding: 6px 10px; border: 1px solid #ddd; text-align: center; min-width: 36px; }}
  th {{ background: #eee; }}
  td {{ font-variant-numeric: tabular-nums; }}
  .meta {{ color: #555; margin-bottom: 16px; }}
</style></head><body>
<h2>{title}</h2>
<div class="meta">
  Images: {eval_report.get('n_images')} ·
  mAP@50: <b>{eval_report.get('mean_ap_50')}</b> ·
  ECE: <b>{eval_report.get('expected_calibration_error')}</b>
  {f"· KS drift: <b>{eval_report.get('score_drift_ks')}</b>" if 'score_drift_ks' in eval_report else ''}
</div>
<p>Rows = ground-truth class, columns = predicted class.
   Diagonal = correctly classified (TP). Last column = false positives
   (off-diagonal collapsed since the eval report lumps them).</p>
<table>
  <thead><tr>{head}</tr></thead>
  <tbody>
  {''.join(rows_html)}
  </tbody>
</table>
<p style="margin-top:32px;color:#888;font-size:12px">
  Generated by scripts/confusion_matrix_view.py
</p>
</body></html>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("eval_json", help="Path to eval_csi.py output JSON")
    ap.add_argument("out_html", help="Path to write the HTML")
    args = ap.parse_args()

    eval_report = json.loads(Path(args.eval_json).read_text())
    html = render_html(eval_report)
    Path(args.out_html).write_text(html, encoding="utf-8")
    print(f"[confusion] wrote {args.out_html}")


if __name__ == "__main__":
    main()
