"""/api/presets/* endpoints — auto-extracted.

Auto-extracted from app.py by _router_split.py 2026-05-01.
Each handler does a late `import app as _app` to access module-level
globals after app.py has finished initialisation.
"""
from __future__ import annotations

import asyncio
import io
import json
import math
import os
import random
import re
import shutil
import sqlite3 as _sqlite3
import subprocess
import sys
import threading
import time
import urllib.parse
import uuid
import zipfile
from datetime import datetime
from pathlib import Path

import cv2
import numpy as np
import torch
from fastapi import APIRouter, File, Form, HTTPException, UploadFile
from fastapi.responses import (
    FileResponse, HTMLResponse, PlainTextResponse, Response, StreamingResponse,
)
from pydantic import BaseModel, Field

from core import (
    DB, JobQueue, JobRow, JobRunner, ModelRow, ProjectRow,
    annotation_picker as picker_core,
    alerts as alerts_core,
    cameras as camera_registry,
    disk as disk_core,
    discovery as discovery_core,
    events as events_core,
    face_blur as face_blur_core,
    machines as machines_core,
    machine_alerts as machine_alerts_core,
    machine_reports as machine_reports_core,
    machine_tracker as machine_tracker_core,
    notify as notify_core,
    picker_scheduler as picker_sched,
    registry as registry_core,
    swiss as swiss_core,
    taxonomy as taxonomy_core,
    util_report_scheduler as util_report_sched,
    watchdog as watchdog_core,
    zones as zones_core,
)
from core.notify import build_audit_report, send_email, send_webhook
from core.playground import inspect_model, predict_on_image
from core.presets import class_index as preset_class_index
from core.presets import get_preset, list_presets
from core.seed import SUGGESTED, install_suggested, seed_existing_models

router = APIRouter(tags=["presets"])

@router .get ("/api/presets")
def api_list_presets ():
    import app as _app
    return list_presets ()

@router .get ("/api/presets/{name}")
def api_get_preset (name :str ):
    import app as _app
    try :
        return get_preset (name )
    except FileNotFoundError :
        raise HTTPException (404 ,f"Preset not found: {name }")

@router .get ("/api/presets/{name}/data-yaml")
def api_preset_data_yaml (name :str ):
    """Generate a starter Ultralytics-format `data.yaml` for this preset's
    taxonomy. The user puts it next to their CVAT-exported train/ and val/
    folders, then trains via the Train tab."""
    import app as _app
    try :
        preset =get_preset (name )
    except FileNotFoundError :
        raise HTTPException (404 )
    classes =preset .get ("classes",[])
    lines =[
    "# Generated by Arclap Vision Suite — drop next to your CVAT export's train/ and val/",
    f"# Preset: {preset .get ('title',name )}",
    "",
    "path: .",
    "train: train/images",
    "val: val/images",
    "",
    f"nc: {len (classes )}",
    "names:",
    ]
    for c in classes :
        lines .append (f"  {c ['id']}: {c ['en']}  # {c .get ('de','')}")
    return Response (content ="\n".join (lines )+"\n",media_type ="text/yaml")
