"""/api/presets/* endpoints — auto-extracted.

Auto-extracted from app.py by _router_split.py 2026-05-01.
Each handler does a late `import app as _app` to access module-level
globals after app.py has finished initialisation.
"""
from __future__ import annotations

import io
import json
import os
import re
import shutil
import sqlite3 as _sqlite3
import threading
import time
import zipfile
from pathlib import Path

import torch
from fastapi import APIRouter, File, Form, HTTPException, UploadFile
from fastapi.responses import (
    FileResponse, HTMLResponse, PlainTextResponse, Response, StreamingResponse,
)
from pydantic import BaseModel, Field

from core import (
    DB, JobQueue, JobRow, JobRunner, ModelRow, ProjectRow,
    annotation_picker as picker_core,
    alerts as alerts_core,
    cameras as camera_registry,
    disk as disk_core,
    discovery as discovery_core,
    events as events_core,
    machine_alerts as machine_alerts_core,
    registry as registry_core,
    swiss as swiss_core,
    watchdog as watchdog_core,
    zones as zones_core,
)

router = APIRouter(tags=["presets"])

@router.get("/api/presets")
def api_list_presets():
    import app as _app
    return list_presets()

@router.get("/api/presets/{name}")
def api_get_preset(name: str):
    import app as _app
    try:
        return get_preset(name)
    except FileNotFoundError:
        raise HTTPException(404, f"Preset not found: {name}")

@router.get("/api/presets/{name}/data-yaml")
def api_preset_data_yaml(name: str):
    """Generate a starter Ultralytics-format `data.yaml` for this preset's
    taxonomy. The user puts it next to their CVAT-exported train/ and val/
    folders, then trains via the Train tab."""
    import app as _app
    try:
        preset = get_preset(name)
    except FileNotFoundError:
        raise HTTPException(404)
    classes = preset.get("classes", [])
    lines = [
        "# Generated by Arclap Vision Suite — drop next to your CVAT export's train/ and val/",
        f"# Preset: {preset.get('title', name)}",
        "",
        "path: .",
        "train: train/images",
        "val: val/images",
        "",
        f"nc: {len(classes)}",
        "names:",
    ]
    for c in classes:
        lines.append(f"  {c['id']}: {c['en']}  # {c.get('de', '')}")
    return Response(content="\n".join(lines) + "\n", media_type="text/yaml")
